### ISSUE TITLE
Bug in dnlib

### ISSUE THREAD

**Issue by Arakis** [mosa/MOSA-Project#155] opened 2015-01-21 16:16 UTC
Because of the switch statement in `DeviceDriverRegitry.cs:170`, the mono compiler needs the **predefined** `System.Collections.Generic.Dictionary` type. When adding this type to korlib (and all the dependency classes, like `KeyValuePair`), dnlib hangs in an endless loop.

I compiled dnlib from kiootic's fork without any modification to get a better stack trace.

http://pastebin.com/KbmyA7Lv

If you wish, i can provide you my added source files to korlib.

**Comment by charsleysa** [comment] 2015-01-22 02:42
Try merging in the updates from the main dnlib repo into kiootic's dnlib repo.

There will be merge conflicts that you will have to resolve but they may have already fixed the bug in the main repo.

**Comment by tgiphil** [comment] 2015-01-22 06:04
It may be faster to re-apply the changes manually; as it appears similar patches were apply since kiootic's work. And the merge is huge with conflicts.

**Comment by kiootic** [comment] 2015-01-22 08:15
It seems like the problem is in the generic instantiation process. Please upload the added source files so that I could look into it.

**Comment by Arakis** [comment] 2015-01-22 12:50
Here are the files, i commited to my fork:
https://github.com/Arakis/MOSA-Project/commit/38e32a7dad4e2f463b61422626b4988f15394062

**Comment by kiootic** [comment] 2015-01-24 15:34
It should be fixed now.

**Comment by charsleysa** [comment] 2015-01-25 06:51
Closing due to issue being fixed by 9f9d007e141f48dfe9c2507ed5c60d923fb8b8b6 and d44db19f6031e73195148ef3d187c4cc82901a57.

**Closed by charsleysa** 2015-01-25 06:51 UTC
Labels: Bug
