### ISSUE TITLE
Bugs in compiler

### ISSUE THREAD

**Issue by Arakis** [mosa/MOSA-Project#177] opened 2015-01-29 17:18 UTC
All bugs are tested with the state of feeaae5b9fe21a40b6eca08945b570bc7fb2489f and CoolWorld OS.

1. ~~in `GDT.cs`, search for `REMOVE_ME'  and remove the unneeded dummy block. After that, compiler crashes with exception: (see far below)~~
2. You will see, CoolWorld demo shows 0 MB available memory, when using my new GDT class. But gdt table memory area are exact equals. Uncomment `Panic.DumpMemory(gdtTableAddress);` to check this. I cannot exclude, that there's a bug in my GDT-Table implementation, but it can also be a bug in the compiler.
3. In `PageTable.cs`, search for `COMPILER_BUG` and uncomment it. After that, the kernel crashes. This is because the adress will be increpmented in 1-byte, instead of 4-byte. In c#, in pointer artimethic, the structure size will used as increpment size.
4. ~~In `PageTable.cs`, uncomment `Panic.DumpMemory(gdtTableAddress);`in `PageTable.Setup()`. Goto `Panic.cs`, uncomment `COMPILER_BUG` and comment the line below `//workarround: separate method`. You will see, that the condition will never be true, but it has to be true in lots of cases.~~
5. There are other bugs, when you call `Panic.Message(number.ToString("X"))` (in `Boot.cs`, it will see the title `*** Debug Message ***` twice. This occurs only, when you do this before kernel init. Is there any way to generate Hex values as strings, before `Kernel.Setup`? Why this works, when you print out the generated string from ToString(X) directly to console, without calling another method? Could it bee, that before kernel init, there's only "one" string reserved and it will be overwritten?
6. Goto `Panic.cs` and uncomment `Mosa.Kernel.Helpers.InternalPanic.ExceptionHandler = Error;` in `Panic.Setup`. After that, qemu will be in a boot loop. You should know, that this is only an assignment, in the current state the delgate will not invoked.

```
Exception: System.ArgumentOutOfRangeException: Der Index lag außerhalb des Bereichs. Er muss nicht negativ und kleiner als die Auflistung sein.
Parametername: index
   bei System.Collections.BitArray.Set(Int32 index, Boolean value)
   bei Mosa.Compiler.Framework.RegisterAllocator.BaseRegisterAllocator.ComputeLocalLiveSets() in c:\GitHub\MOSA-Project\Source\Mosa.Compiler.Framework\RegisterAllocator\BaseRegisterAllocator.cs:Zeile 447.
   bei Mosa.Compiler.Framework.RegisterAllocator.BaseRegisterAllocator.Start() in c:\GitHub\MOSA-Project\Source\Mosa.Compiler.Framework\RegisterAllocator\BaseRegisterAllocator.cs:Zeile 123.
   bei Mosa.Compiler.Framework.Stages.GreedyRegisterAllocatorStage.Run() in c:\GitHub\MOSA-Project\Source\Mosa.Compiler.Framework\Stages\GreedyRegisterAllocatorStage.cs:Zeile 23.
   bei Mosa.Compiler.Framework.BaseMethodCompilerStage.Mosa.Compiler.Framework.IMethodCompilerStage.Execute() in c:\GitHub\MOSA-Project\Source\Mosa.Compiler.Framework\BaseMethodCompilerStage.cs:Zeile 136.
   bei Mosa.Compiler.Framework.BaseMethodCompiler.Compile() in c:\GitHub\MOSA-Project\Source\Mosa.Compiler.Framework\BaseMethodCompiler.cs:Zeile 247.
   bei Mosa.Compiler.Framework.BaseCompiler.CompileMethod(MosaMethod method, BasicBlocks basicBlocks, InstructionSet instructionSet, Int32 threadID) 
```

**Comment by Arakis** [comment] 2015-01-29 17:44
Updated commit

**Comment by tgiphil** [comment] 2015-01-30 03:20
The first bug is a known issue #174.

I'll respond separately after I review each of them.

**Comment by tgiphil** [comment] 2015-01-30 07:24
Regarding the first issue with PageTable.cs, it should increment by 1 because the type is an integer and not a pointer. If it were a pointer, it would increment by 4.

**Comment by tgiphil** [comment] 2015-01-30 07:43
Regarding Panic.Message(number.ToString("X")), this fails because memory allocation has not been setup yet by the kernel. No strings or objects can be created until the Kernel.Setup() or at least VirtualPageAllocator.Setup() step has been executed.

**Comment by tgiphil** [comment] 2015-01-30 07:45
Regarding Mosa.Kernel.Helpers.InternalPanic.ExceptionHandler = Error, same reason as above. This requires a delegate - and delegate need to be instantiated.

**Comment by tgiphil** [comment] 2015-01-30 07:53
4 - Please generate the smallest unit test that shows this error. I looked over the results and the resulting code appears to be okay; however, it's a long method and something may have been missed. A good unit test would be very helpful.

**Comment by tgiphil** [comment] 2015-01-30 07:56
2 - This may be related to #174. So let's wait until #174 is resolved before investigating further.

**Comment by tgiphil** [comment] 2015-01-31 08:14
Please retest 1.

**Comment by Arakis** [comment] 2015-01-31 18:50
3 - No, its declaed as pointer:
```
internal static PageDirectoryEntry* pageDirectoryEntries;
```
And will be acced here:
```
			#region COMPILER_BUG?
			return pageDirectoryEntries + index;
			#endregion COMPILER_BUG?
```
The line below (with the uint adress intead of the pointer) is only, becaues the wanted line does not work (wrong increpment).

**Comment by Arakis** [comment] 2015-01-31 19:26
2 - I tested it with your latest patches - still the same.

**Comment by Arakis** [comment] 2015-01-31 19:30
1 - It works now

**Comment by Arakis** [comment] 2015-01-31 20:48
4 - I made a unit test in TestWorld:
d5a37e5759bac01af9b0711312284e0ec08601d5
```C#
public static bool ConditionalBug()
{
	uint address = 0x0B8050; //it's the display memory, but you can use any other adress, so far it's no critical area
	Mosa.Platform.Internal.x86.Native.Set8(address, 81); //set ascii 'Q'
	var num = Mosa.Platform.Internal.x86.Native.Get8(address); //get the 'Q' back

	#region COMPILER_BUG

	if (num >= 32 && num < 128) //COMPILER_BUG: This conditinal expression will not resolved correctly!
		return true;
	else
		return false;

	#endregion COMPILER_BUG
}
```

**Comment by tgiphil** [comment] 2015-02-01 01:49
Confirmed; 4 is a compiler bug.

**Comment by tgiphil** [comment] 2015-02-01 06:19
Resolving 4 with  #181.

**Comment by charsleysa** [comment] 2015-02-21 06:52
Closing as too broad and too difficult to keep track of.

If these issues still exist please open a new issue for each one.

**Closed by charsleysa** 2015-02-21 06:52 UTC
Labels: Bug, Discussion
