### ISSUE TITLE
MOSA Launcher fails to create boot images

### ISSUE THREAD

**Issue by charsleysa** [mosa/MOSA-Project#248] opened 2015-11-03 08:52 UTC
MOSA Launcher fails to create boot images.

There seems to be a bug in the BootImage utility library which fails to generate images properly.

**Comment by tgiphil** [comment] 2015-11-18 09:18
The issue is the new Syslinux v6.03 installation has changed significantly since v3.72. 

Until this is resolved, the default build is ISO to avoid the issue for now.

**Comment by tgiphil** [comment] 2015-11-22 16:27
Added back previous version of Syslinux as an option. So virtual disk images (along with ISO) are now available. I will close this ticket and create new ticket for adding Syslinux v3.72 support.

**Closed by tgiphil** 2015-11-22 16:27 UTC
Labels: Bug
